Feature cs 4
ccem-dev/communication-service pull request #17
Opened 2020-07-01 17:07 UTC by brenoscheffer

Comunicação com o Elasticsearch para funcionalidade de Issues

2020-07-01 17:50 UTC, drferreira commented on source/app/controllers/ProjectCommunicationController.js
> +                    //TODO check what to return. Id only?
Este TODO foi resolvido? Se sim, deve ser removido.

2020-07-01 17:50 UTC, drferreira commented on source/app/dev-env/todo.txt
> +- inserção e modificação levam documento para final do array
Acredito que este arquivo foi por engano.

2020-07-01 17:51 UTC, drferreira commented on source/app/models/IssueFactory.js
> +/** @namespace application.app.models.IssueFactory**/
comentario para remoção

2020-07-01 17:51 UTC, drferreira commented on source/app/models/IssueFactory.js
> +                        // _id: {type: "keyword"},
comentario para remoção

2020-07-01 17:51 UTC, drferreira commented on source/app/models/MessageFactory.js
> +                        // _id: {type: 'keyword'},
comentario para remoção

2020-07-01 17:51 UTC, drferreira commented on source/app/routes/ProjectCommunicationRestService.js
> +    //cria a issue
comentario para remoção

2020-07-01 17:52 UTC, drferreira commented on source/app/routes/ProjectCommunicationRestService.js
> +    //busca issue pelo id da issue
comentario para remoção

2020-07-01 17:52 UTC, drferreira commented on source/app/routes/ProjectCommunicationRestService.js
> +    //busca issue pelo  id do sender
comentario para remoção

2020-07-01 17:52 UTC, drferreira commented on source/app/routes/ProjectCommunicationRestService.js
> +    //busca issue pelo  id do group
comentario para remoção (revisar todos do serviço)

2020-07-01 17:52 UTC, drferreira commented on source/app/services/ElasticsearchIndexes.js
> +/** @namespace application.app.services.ElasticsearchIndexes **/
comentario para remoção

2020-07-01 17:53 UTC, drferreira commented on source/app/services/ElasticsearchService.js
> +    //use self for stateful variables
comentario para remoção

2020-07-01 17:53 UTC, drferreira commented on source/app/services/IssueService.js
> +/** @namespace application.app.services.IssueService **/
comentario para remoção

2020-07-01 17:53 UTC, drferreira commented on source/app/services/IssueService.js
> +                            //order
comentario para remoção

2020-07-01 17:53 UTC, drferreira commented on source/app/services/IssueService.js
> +                            //order
comentario para remoção

2020-07-01 17:53 UTC, drferreira commented on source/app/services/IssueService.js
> +            //update to OPEN, CLOSED, FINALIZED
comentario para remoção

2020-07-01 17:54 UTC, drferreira commented on source/app/services/MessageService.js
> +/** @namespace application.app.services.MessageService **/
comentario para remoção

2020-07-01 17:54 UTC, drferreira commented on source/app/utils/ShutdownEventService.js
> +    //use self for stateful variables
comentario para remoção

2020-07-01 17:54 UTC, drferreira commented on source/package.json
> +    "@elastic/elasticsearch": "^7.7.1",
Remover ^ de pendencia.

2020-07-01 17:55 UTC, drferreira commented on source/package.json
> +    "sucrase": "^3.15.0"
remover ^ de dependencia.

2020-07-01 17:56 UTC, drferreira commented on source/test/data/json-importer.js
> +let data = {};
Json importer deve ser enviado?

2020-07-01 17:56 UTC, drferreira commented on source/test/routes/ProjectCommunicationRest-spec.js
> +        // .expect('Content-Type', /json/)
comentario para remoção

2020-07-01 17:56 UTC, drferreira commented on source/test/routes/ProjectCommunicationRest-spec.js
> +        // .expect(200);
comentario para remoção

2020-07-01 17:56 UTC, drferreira commented on source/test/routes/ProjectCommunicationRest-spec.js
> +        // .expect(200);
comentario para remoção

2020-07-01 17:56 UTC, drferreira commented on source/test/routes/ProjectCommunicationRest-spec.js
> +        // .expect(200);
comentario para remoção

2020-07-01 17:58 UTC, drferreira requested changes
Alguns itens para alteração descritos no código.
Parabens aos envolvidos ficou muito bom o código, principalmente a organização do controler.

2020-07-01 18:58 UTC, adonisgarcia commented
Todos que tem @namespace é uma declaração, sem ela o ide não reconhece o script.

2020-07-01 20:22 UTC, drferreira commented on source/test/data/json-importer.js
> +let data = {};
Ignorar este cara @adonisgarcia

2020-07-01 20:43 UTC, adonisgarcia commented on source/test/data/json-importer.js
> +let data = {};
ok

2020-07-02 13:08 UTC, adonisgarcia commented
O @namespace tem relação com JSDoc.

Syntax
@namespace [[{<type>}] <SomeName>]

Overview
The @namespace tag indicates that an object creates a namespace for its members. You can also write a virtual JSDoc comment that defines a namespace used by your code.

Exemple:

/** @namespace window */

/**

Shorthand for the alert function.

Refer to it as {@link window."!"} (note the double quotes).
*/
window["!"] = function(msg) { alert(msg); };
 

Fonte: https://jsdoc.app/tags-namespace.html

2020-07-02 13:25 UTC, drferreira approved these changes

2020-07-02 13:25 UTC, merged